// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr0b25tZph71qFyy8ajGy285gDoHN6Gfw',
    appId: '1:618354486999:web:f94b8f8f057192c70c0a92',
    messagingSenderId: '618354486999',
    projectId: 'shawl-f6d46',
    authDomain: 'shawl-f6d46.firebaseapp.com',
    storageBucket: 'shawl-f6d46.appspot.com',
    measurementId: 'G-Y95ZKF2BNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0kxRU4PlpEIEQ1UVmi3T-brvrwfUdjsc',
    appId: '1:618354486999:android:34bfa4b7c57087f80c0a92',
    messagingSenderId: '618354486999',
    projectId: 'shawl-f6d46',
    storageBucket: 'shawl-f6d46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWtoJP8DIyuQ2ucCGOrBWmkoYrY66DFpU',
    appId: '1:618354486999:ios:e8b1dd634f7c12ba0c0a92',
    messagingSenderId: '618354486999',
    projectId: 'shawl-f6d46',
    storageBucket: 'shawl-f6d46.appspot.com',
    iosClientId: '618354486999-k8okp109f87jis7jsvcr7j44t5q6806v.apps.googleusercontent.com',
    iosBundleId: 'com.lm.shawl.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWtoJP8DIyuQ2ucCGOrBWmkoYrY66DFpU',
    appId: '1:618354486999:ios:45b4a83306cc76b10c0a92',
    messagingSenderId: '618354486999',
    projectId: 'shawl-f6d46',
    storageBucket: 'shawl-f6d46.appspot.com',
    iosClientId: '618354486999-al840p2kh6ofr76eq87v94t3dn3dcgk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shawlProd.RunnerTests',
  );
}
